# Generated by Django 5.2.8 on 2025-11-20 09:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название критерия')),
                ('description', models.TextField(blank=True)),
                ('criterion_type', models.CharField(choices=[('Количественный', 'Количественный'), ('Качественный', 'Качественный')], max_length=20)),
                ('max_value', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('direction', models.CharField(choices=[('Максимизирующий', 'Максимизирующий'), ('Минимизирующий', 'Минимизирующий')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО руководителя')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name='УНП')),
                ('org_type', models.CharField(max_length=50, verbose_name='Тип организации')),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('verification_status', models.CharField(choices=[('На проверке', 'На проверке'), ('Подтверждено', 'Подтверждено'), ('Отклонено', 'Отклонено')], default='На проверке', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_organizations', to='tenders.manager')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('Подана', 'Подана'), ('Проверяется', 'Проверяется'), ('Подтверждена', 'Подтверждена'), ('Отклонена', 'Отклонена')], default='Подана', max_length=20)),
                ('final_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='tenders.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('verification', 'Для верификации организации'), ('proposal', 'Для заявки на тендер')], default='proposal', max_length=20)),
                ('name', models.CharField(max_length=100, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verification_status', models.CharField(choices=[('На проверке', 'На проверке'), ('Подтвержден', 'Подтвержден'), ('Отклонен', 'Отклонен')], default='На проверке', max_length=20)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenders.manager')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='tenders.organization')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenders.proposal')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Номер договора')),
                ('signed_date', models.DateField(verbose_name='Дата подписания')),
                ('pdf_file', models.FileField(upload_to='contracts/', verbose_name='PDF договора')),
                ('status', models.CharField(choices=[('Подписан', 'Подписан'), ('Расторгнут', 'Расторгнут')], default='Подписан', max_length=20)),
                ('proposal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenders.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название тендера')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Открыт', 'Открыт'), ('В оценке', 'В оценке'), ('Закрыт', 'Закрыт')], default='Открыт', max_length=20)),
                ('method', models.CharField(choices=[('AHP', 'AHP'), ('TOPSIS', 'TOPSIS')], max_length=20, verbose_name='Метод оценки')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='tenders.organization')),
            ],
        ),
        migrations.AddField(
            model_name='proposal',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='tenders.tender'),
        ),
        migrations.CreateModel(
            name='TenderCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.criterion')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='tenders.tender')),
            ],
            options={
                'unique_together': {('tender', 'criterion')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('Фирма', 'Фирма'), ('Поставщик', 'Поставщик'), ('Менеджер', 'Менеджер')], default='Фирма', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='tenders_user_groups', related_query_name='tenders_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='tenders_user_permissions', related_query_name='tenders_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='tenders.user'),
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to='tenders.user'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comment', models.TextField(blank=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenders.manager')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='tenders.proposal')),
                ('tender_criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.tendercriterion')),
            ],
            options={
                'unique_together': {('proposal', 'tender_criterion')},
            },
        ),
    ]
