# Generated by Django 5.2.8 on 2025-12-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='approval_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
